import {test,expect} from '@playwright/test';
import fs from 'node:fs';
const headers={'X-Mandarin-Client':'local-ui'};
test.beforeEach(async({request})=>{const backup=await(await request.get('/api/backup')).json();backup.objects=[];backup.events=[];const pack=JSON.parse(fs.readFileSync('content/foundation.pack.json','utf8'));backup.packages=[{id:pack.content.id,version:pack.content.version,payload:JSON.stringify(pack)}];await request.post('/api/restore',{headers,data:backup});});
test('chuyển bài, cuối chủ đề, cuối lộ trình; reload và Back giữ đúng bài',async({page,request})=>{
 const c=await(await request.get('/api/content')).json();const all=c.units.flatMap((u:any)=>u.lessons);const run='TEST-ROUTES';
 for(const [index,phase] of [[0,'summary'],[1,'exercise'],[3,'summary'],[47,'summary']] as const)await request.post('/api/objects',{headers,data:{collection:'sessions',id:all[index].id,expected_version:0,data:{index:phase==='exercise'?2:0,phase,run,answers:[],draft:phase==='exercise'?'TEST draft':''}}});
 await page.goto('/#learn/'+all[0].id);await page.getByRole('button',{name:/Bài tiếp theo/}).click();await expect(page).toHaveURL(new RegExp(all[1].id));await expect(page.getByRole('textbox',{name:'Câu trả lời',exact:true})).toHaveValue('TEST draft');await page.reload();await expect(page.getByRole('textbox',{name:'Câu trả lời',exact:true})).toHaveValue('TEST draft');await page.goBack();await expect(page.getByText('Bạn đã đi hết bài học')).toBeVisible();
 await page.goto('/#learn/'+all[3].id);await page.getByRole('button',{name:/Sang chủ đề tiếp theo/}).click();await expect(page).toHaveURL(new RegExp(all[4].id));await expect(page.getByRole('button',{name:'Bắt đầu luyện tập'})).toBeVisible();
 await page.goto('/#learn/'+all[47].id);await expect(page.getByRole('link',{name:/đi hết lộ trình/})).toBeVisible();expect((await(await request.get('/api/state')).json()).events).toHaveLength(0);
});
test('nét cạnh từ, từng chữ, giảm chuyển động và không lộ bộ thủ trước đáp án',async({page,request})=>{
 await page.emulateMedia({reducedMotion:'reduce'});const blocked:string[]=[];await page.route('**/*',r=>{if(new URL(r.request().url()).hostname!=='127.0.0.1'){blocked.push(r.request().url());return r.abort();}return r.continue();});
 const c=await(await request.get('/api/content')).json();const l=c.units[0].lessons[0];await page.goto('/#learn/'+l.id);const word=page.getByRole('complementary',{name:'Nét chữ 你好',exact:true});await expect(word.getByRole('img')).toHaveAttribute('aria-label',/你/);await expect(word.getByRole('button',{name:'Tạm dừng',exact:true})).toHaveCount(0);await word.getByRole('button',{name:'好',exact:true}).click();await expect(word.getByRole('img')).toHaveAttribute('aria-label',/好/);await word.getByRole('button',{name:'Nét kế'}).click();await expect(word).toContainText('1/6 nét');await page.screenshot({path:'test-results/word-strokes.png',fullPage:false});
 await page.getByRole('button',{name:'Bắt đầu luyện tập'}).click();await expect(page.locator('.exercise .character-study')).toBeVisible();await expect(page.locator('.exercise')).not.toContainText('Bộ thủ tra cứu');await page.getByRole('button',{name:'Xem gợi ý'}).click();await expect(page.locator('.exercise')).toContainText('Bộ thủ tra cứu');await page.getByRole('button',{name:l.exercises[0].answers[0],exact:true}).click();await page.getByRole('button',{name:'Kiểm tra',exact:true}).click();await expect(page.getByText('Đúng rồi!',{exact:true})).toBeVisible();expect((await(await request.get('/api/state')).json()).events[0].assisted).toBe(true);expect(blocked).toEqual([]);
});
test('Pinyin phát file thật offline, ghép âm theo thứ tự, dừng khi đổi âm và mobile',async({page})=>{
 const blocked:string[]=[];await page.route('**/*',r=>{if(new URL(r.request().url()).hostname!=='127.0.0.1'){blocked.push(r.request().url());return r.abort();}return r.continue();});
 await page.addInitScript(()=>{(window as any).__played=[];const Real=window.Audio;window.Audio=new Proxy(Real,{construct(Target,args){const audio=new Target(...args as []);audio.addEventListener('playing',()=>{(window as any).__played.push(audio.src);(window as any).__audio=audio;});return audio;}});});
 await page.goto('/#pronunciation');await page.getByRole('button',{name:'Nghe đánh vần',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__played.length)).toBe(3);const urls=await page.evaluate(()=>(window as any).__played);expect(urls.map((x:string)=>new URL(x).pathname)).toEqual(['/learning/pinyin/moe/F1.WAV','/learning/pinyin/moe/F22.WAV','/learning/pinyin/syllables/ba1.mp3']);
 await page.getByLabel('Thanh mẫu',{exact:true}).selectOption('n');await page.getByLabel('Vận mẫu',{exact:true}).selectOption('ü');await page.getByRole('button',{name:/Thanh 3 · nǚ/}).click();await expect(page.locator('.syllable-result')).toHaveText('nǚ');await page.getByRole('button',{name:'◖)) Nghe âm tiết',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__audio.src)).toMatch(/nuu3.mp3$/);await page.getByLabel('Thanh mẫu',{exact:true}).selectOption('b');expect(await page.evaluate(()=>(window as any).__audio.paused)).toBe(true);
 await page.getByRole('button',{name:'Mở bảng thanh mẫu × vận mẫu'}).click();await page.getByRole('button',{name:'Chọn âm ju',exact:true}).click();await expect(page.getByLabel('Vận mẫu',{exact:true})).toHaveValue('ü');await page.getByRole('button',{name:'Thanh nhẹ',exact:true}).click();await expect(page.locator('.pinyin-result')).toContainText('chưa có bản ghi thanh nhẹ');
 const catalog=JSON.parse(fs.readFileSync('public/learning/pinyin/catalog.json','utf8'));const missing=catalog.find((s:any)=>Object.values(s.tones).some(v=>!v));const missingTone=Object.keys(missing.tones).find(t=>!missing.tones[t]);
 await page.getByRole('button',{name:'Chọn âm '+missing.base,exact:true}).click();await page.getByRole('button',{name:new RegExp('^Thanh '+missingTone+' ·')}).click();await expect(page.getByRole('button',{name:'◖)) Nghe âm tiết',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Nghe đánh vần',exact:true})).toBeDisabled();await expect(page.locator('.pinyin-result')).toContainText('Chưa có âm mẫu');
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('.pinyin-lab').screenshot({path:'test-results/pinyin-mobile.png'});expect(blocked).toEqual([]);
});
test('ngữ pháp: bài riêng, lưu tiếp tục, gợi ý, sổ lỗi và số bài học không bị tăng',async({page,request})=>{
 const c=await(await request.get('/api/content')).json();const g=c.units[0].grammar[0];await page.goto('/#grammar/'+g.id);await expect(page.locator('.grammar-example')).toHaveCount(3);await page.getByRole('button',{name:'Luyện ngữ pháp (4 câu)'}).click();
 const first=g.exercises[0];await page.getByRole('button',{name:first.choices.find((x:string)=>x!==first.answers[0]),exact:true}).click();await page.getByRole('button',{name:'Kiểm tra ngữ pháp',exact:true}).click();await expect(page.getByText('Cùng xem lại nhé')).toBeVisible();await page.getByRole('button',{name:'Tiếp tục ngữ pháp →'}).click();await page.getByRole('textbox',{name:'Câu trả lời ngữ pháp'}).fill('TEST draft');await page.getByRole('button',{name:'Lưu & tạm dừng'}).click();await expect(page).toHaveURL(/#grammar$/);await page.goto('/#grammar/'+g.id);await expect(page.getByRole('textbox',{name:'Câu trả lời ngữ pháp'})).toHaveValue('TEST draft');
 for(const ex of g.exercises.slice(1)){if(ex===g.exercises[1]){await page.getByRole('button',{name:'Gợi ý ngữ pháp'}).click();await expect(page.locator('.hint')).toBeVisible();await page.reload();await expect(page.locator('.hint')).toBeVisible();}await page.getByRole('textbox',{name:'Câu trả lời ngữ pháp'}).fill(ex.answers[0]);await page.getByRole('button',{name:'Kiểm tra ngữ pháp',exact:true}).click();await page.getByRole('button',{name:'Tiếp tục ngữ pháp →'}).click();}
 await expect(page.getByText('Đã đi hết bài luyện ngữ pháp')).toBeVisible();await page.reload();await expect(page.getByText('Đã đi hết bài luyện ngữ pháp')).toBeVisible();const state=await(await request.get('/api/state')).json();expect(state.events).toHaveLength(4);expect(state.events.filter((e:any)=>e.assisted)).toHaveLength(1);expect(Object.keys(state.objects.cards)).toHaveLength(0);
 await page.goto('/#learn');await expect(page.getByText('0/48 bài đã học')).toBeVisible();await page.goto('/#review');await page.getByRole('button',{name:/Sổ lỗi sai/}).click();await expect(page.getByRole('heading',{name:first.prompt,exact:true})).toBeVisible();await page.goto('/#grammar');await page.getByLabel('Tiến độ ngữ pháp').selectOption('done');await expect(page.locator('.unit-grid article')).toHaveCount(1);await page.screenshot({path:'test-results/grammar-desktop.png'});
});
test('danh mục TBCL phân biệt bài đã soạn và tham chiếu chưa có bài',async({page})=>{
 await page.goto('/#grammar');await page.getByRole('button',{name:'Xem danh mục tham chiếu TBCL'}).click();await expect(page.locator('.roadmap-item')).toHaveCount(24);await expect(page.getByText(/496 kết quả tham chiếu/)).toBeVisible();await page.getByRole('button',{name:'Trang sau',exact:true}).click();await expect(page.getByText('2/21',{exact:true})).toBeVisible();await page.getByLabel('Mức học / cấp nguồn').selectOption('第5級');await expect(page.locator('.roadmap-item').first()).toContainText('第5級');await page.getByLabel('Tìm ngữ pháp',{exact:true}).fill('không tồn tại TEST');await expect(page.locator('.roadmap-item')).toHaveCount(0);
});

test('tiên quyết và lô ngữ pháp lọc theo nhóm, giữ cấp nguồn và dùng được trên mobile offline',async({page,request})=>{
 const c=await(await request.get('/api/content')).json();const blocked:string[]=[];
 await page.route('**/*',r=>{if(new URL(r.request().url()).hostname!=='127.0.0.1'){blocked.push(r.request().url());return r.abort();}return r.continue();});
 const g=c.units.flatMap((u:any)=>u.grammar).find((g:any)=>g.prerequisites.length);
 await page.goto('/#grammar/'+g.id);const prerequisite=page.getByRole('complementary',{name:'Kiến thức tiên quyết'});await prerequisite.getByRole('link').first().click();await expect(page).toHaveURL(new RegExp(g.prerequisites[0]));
 await page.goto('/#grammar');await page.getByLabel('Tiến độ ngữ pháp').selectOption('planned');
 const group='Thời–thể và bổ ngữ';await page.getByLabel('Nhóm kiến thức').selectOption(group);
 const expected=c.grammar_roadmap.filter((r:any)=>r.group===group);await expect(page.getByRole('status').filter({hasText:'kết quả tham chiếu'})).toContainText(expected.length+' kết quả');
 for(const text of await page.locator('.roadmap-item').allTextContents())expect(text).toContain(group);
 const batch=c.grammar_batches.find((b:any)=>b.group===group);await page.getByLabel('Lô biên soạn').selectOption(batch.id);
 await expect(page.locator('.roadmap-item')).toHaveCount(c.grammar_roadmap.filter((r:any)=>r.batch_id===batch.id).length);
 await expect(page.locator('.roadmap-batch')).toHaveCount(1);await page.locator('.roadmap-batch .actions button').first().click();
 await expect(page.getByLabel('Lô biên soạn')).toHaveValue(batch.prerequisites[0]);
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/grammar-roadmap-mobile.png',fullPage:true});expect(blocked).toEqual([]);
 expect((await(await request.get('/api/state')).json()).events).toHaveLength(0);
});
