import {useEffect,useId,useState} from 'react';

type Stroke={outline:string;median:number[][];matrix:number[]};
type CharacterData={character:string;radical:string;decomposition:string;strokes:Stroke[];source:string;reference:string;verification:string;variant:string;copyright?:string;modification?:string;structure_verification?:string};
const descriptions:Record<string,string>={'⿰':'trái – phải','⿱':'trên – dưới','⿲':'trái – giữa – phải','⿳':'trên – giữa – dưới','⿴':'bao kín','⿵':'bao phía trên','⿶':'bao phía dưới','⿷':'bao phía trái','⿸':'bao phía trên/trái','⿹':'bao phía trên/phải','⿺':'bao phía dưới/trái','⿻':'đan xen'};
const radicalNames:Record<string,string>={'人':'nhân · người','亻':'nhân đứng · người','口':'khẩu · miệng','心':'tâm · tim, lòng','手':'thủ · tay','水':'thủy · nước','木':'mộc · cây','火':'hỏa · lửa','土':'thổ · đất','女':'nữ · phụ nữ','言':'ngôn · lời nói','糸':'mịch · tơ','金':'kim · kim loại','食':'thực · ăn','雨':'vũ · mưa','石':'thạch · đá','足':'túc · chân','宀':'miên · mái nhà','广':'nghiễm · mái che','穴':'huyệt · hang','日':'nhật · mặt trời','月':'nguyệt · trăng','衣':'y · áo','門':'môn · cửa','辵':'sước · đi','艸':'thảo · cỏ','目':'mục · mắt','耳':'nhĩ · tai','貝':'bối · vỏ sò','馬':'mã · ngựa','竹':'trúc · tre'};
const componentNames:Record<string,string>={'𠃌':'nét gập có móc','䜌':'(糸 – 言 – 糸)','𧾷':'dạng bên trái của 足','龶':'ba nét ngang với nét dọc xuyên','龸':'phần trên của 尚','亼':'(人 trên 一)','尌':'(壴 trái, 寸 phải)'};
function decompositionDescription(value:string){return Array.from(value).map(c=>descriptions[c]?`[${descriptions[c]}]`:componentNames[c]||c).join(' ');}

export function CharacterStudy({text,explain=true,compact=false}:{text:string;explain?:boolean;compact?:boolean}){
 const chars=Array.from(text).filter(c=>/\p{Script=Han}/u.test(c));const [selected,setSelected]=useState(0),[data,setData]=useState<CharacterData|null>(null),[error,setError]=useState(''),[progress,setProgress]=useState(0),[playing,setPlaying]=useState(false),[slow,setSlow]=useState(false);const uid=useId().replace(/:/g,'');
 const char=chars[selected]||chars[0];
 useEffect(()=>{setSelected(0);},[text]);
 useEffect(()=>{if(!char)return;const controller=new AbortController();setData(null);setError('');setProgress(0);setPlaying(false);
  fetch(`/learning/characters/${char.codePointAt(0)}.json`,{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error('Chưa có mẫu nét cho chữ này.');return r.json();}).then(d=>{if(controller.signal.aborted)return;setData(d);setPlaying(!window.matchMedia('(prefers-reduced-motion: reduce)').matches);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[char]);
 useEffect(()=>{if(!playing||!data)return;let frame=0,previous=performance.now();const tick=(now:number)=>{const delta=(now-previous)/(slow?1800:1000);previous=now;setProgress(p=>Math.min(data.strokes.length,p+delta));frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,data,slow]);
 useEffect(()=>{if(data&&progress>=data.strokes.length)setPlaying(false);},[progress,data]);
 if(!char)return null;
 return <aside className={'character-study '+(compact?'compact':'')} aria-label={'Nét chữ '+text}>
  {chars.length>1&&<div className="character-tabs" role="group" aria-label="Chọn chữ trong từ">{chars.map((c,i)=><button key={i} aria-pressed={i===selected} onClick={()=>setSelected(i)} lang="zh-TW">{c}</button>)}</div>}
  <div className="stroke-stage">{data?<svg viewBox="0 0 1024 1024" role="img" aria-label={`Thứ tự ${data.strokes.length} nét chữ ${char}`}><path d="M512 0V1024M0 512H1024" stroke="#dddcc9" strokeDasharray="14 14"/>
   {data.strokes.map((s,i)=><g key={i} transform={'matrix('+s.matrix.join(' ')+')'}><defs><clipPath id={`${uid}-${i}`}><path d={s.outline}/></clipPath></defs><path d={s.outline} fill={i<Math.floor(progress)?'#245f50':'#e2e7dc'}/>{i===Math.floor(progress)&&<path clipPath={`url(#${uid}-${i})`} d={'M'+s.median.map(p=>p.join(',')).join(' L')} fill="none" stroke="#d88145" strokeWidth="140" strokeLinecap="round" strokeLinejoin="round" pathLength="1" strokeDasharray="1" strokeDashoffset={1-Math.min(1,(progress-i)/.8)}/>}</g>)}
  </svg>:<p>{error||'Đang mở mẫu nét…'}</p>}</div>
  {data&&<><small>{Math.min(Math.ceil(progress),data.strokes.length)}/{data.strokes.length} nét · {char}</small><div className="actions stroke-controls"><button aria-label={'Phát lại nét '+char} onClick={()=>{setProgress(0);setPlaying(true);}}>↻ Phát lại</button><button onClick={()=>setPlaying(!playing)} disabled={progress>=data.strokes.length}>{playing?'Tạm dừng':'Phát tiếp'}</button><button onClick={()=>{setPlaying(false);setProgress(p=>Math.min(data.strokes.length,Math.floor(p)+1));}}>Nét kế</button><label><input type="checkbox" checked={slow} onChange={e=>setSlow(e.target.checked)}/> Chậm</label></div>
  {explain&&<div className="character-explanation"><p><strong>Bộ thủ tra cứu:</strong> <span lang="zh-TW">{data.radical}</span>{radicalNames[data.radical]?' — '+radicalNames[data.radical]:''}</p><p><strong>Cấu tạo hình chữ:</strong> {data.decomposition?decompositionDescription(data.decomposition):'Chữ đơn thể; không tách thêm trong mẫu này.'}</p><small>Các thành phần giúp nhận ra hình chữ; không phải tất cả đều là bộ thủ. Chưa diễn giải nguồn gốc hoặc vai trò biểu âm/biểu nghĩa nếu chưa có nguồn.</small></div>}
  <details><summary>Nguồn mẫu nét</summary><small>{data.verification}. {data.structure_verification} Mẫu bổ sung có thể được ghép/chỉnh từ hình có giấy phép; không chấm thư pháp.</small><p><a href={data.source} target="_blank" rel="noreferrer">AnimCJK · APL/LGPL</a> · <a href={data.reference} target="_blank" rel="noreferrer">Đối chiếu MOE</a></p><p>{data.copyright}. Mẫu nét được cung cấp không bảo hành; được sao chép/chỉnh sửa theo <a href="/learning/licenses/animcjk/APL/english/ARPHICPL.TXT" target="_blank" rel="noreferrer">giấy phép APL local</a>.</p>{explain&&<small>{data.modification}</small>}</details></>}
 </aside>;
}
