import {useRef,useState} from 'react';
import {useApp} from '../context';
import type {Exercise,Lesson,Session,Unit,Word} from '../core/types';
import {canSubmitKey,errorCategory,eventFor,grade,newSchedule} from '../core/learning';
import {Handwriting,LayerText,Recorder,Speak} from './common';
import {chatModel} from '../adapters/local';
import {useActiveTimer} from '../core/useActiveTimer';

export function Learn(){
  const {content,state}=useApp();const [selected,setSelected]=useState<{unit:Unit;lesson:Lesson}|null>(null),[search,setSearch]=useState('');
  if(selected)return <LessonView key={selected.lesson.id} {...selected} onBack={()=>setSelected(null)}/>;
  const complete=Object.values(state.objects.sessions).filter(s=>s.data.phase==='summary').length;
  const resume=content.units.flatMap(u=>u.lessons.map(l=>({unit:u,lesson:l}))).find(({lesson})=>{const s=state.objects.sessions[lesson.id]?.data;return s&&s.phase!=='summary';});
  return <><div className="hero"><div><span className="eyebrow">MỖI CÂU NÓI, MỘT KẾT NỐI</span><h1>Một chút Hoa ngữ.<br/>Một Đài Loan gần hơn.</h1><p>Học theo nhịp của bạn. Từ lời chào đầu tiên đến những cuộc trò chuyện mỗi ngày.</p>{resume&&<button className="primary" onClick={()=>setSelected(resume)}>Tiếp tục bài đang học →</button>}<div className="hero-meta"><span>Phồn thể · Pinyin · Tiếng Việt</span><span>Học ngay trên máy của bạn</span></div></div><div className="island-art" aria-label="Nhân vật hòn đảo nhỏ"><span className="cloud c1"/><span className="cloud c2"/><div className="sun"/><div className="island"><div className="eyes">• •</div><div className="smile">⌣</div></div><div className="water w1"/><div className="water w2"/><span className="art-caption" lang="zh-TW">慢慢來，一起學。</span></div></div><div className="section-title"><div><span className="eyebrow">LỘ TRÌNH NỀN TẢNG</span><h2>Bước đầu đến Đài Loan</h2></div><span className="tag">{complete}/{content.units.length*4} bài đã học</span></div><p className="notice">Nội dung bản nháp do AI hỗ trợ biên soạn, chưa có giáo viên thẩm định. Phạm vi nền tảng; chưa xác nhận đạt A1.</p><label className="search">⌕ <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm chủ đề, Hán tự, Pinyin hoặc nghĩa…" aria-label="Tìm nội dung"/></label><div className="unit-grid">{content.units.filter(u=>(u.title+' '+u.words.map(w=>w.hanzi+w.pinyin+w.vi).join(' ')).toLowerCase().includes(search.toLowerCase())).map((unit,i)=>{
    const known=state.objects.placement['latest']?.data.skipped?.includes(unit.id);
    return <article className="unit-card" key={unit.id}><div className="unit-top"><span className="unit-number">{String(i+1).padStart(2,'0')}</span><span className="unit-character" lang="zh-TW">{unit.character}</span></div><h3>{unit.title}</h3><p>{unit.description}</p>{known&&<span className="tag">Đầu vào: gợi ý có thể bỏ qua</span>}<div className="lesson-list">{unit.lessons.map((l,j)=><button key={l.id} onClick={()=>setSelected({unit,lesson:l})}><span>{state.objects.sessions[l.id]?.data.phase==='summary'?'✓':j+1}</span>{l.title}<b>↗</b></button>)}</div><div className="unit-bottom">{unit.words.length} mục từ · {unit.grammar.length} cấu trúc · 4 bài</div></article>;
  })}</div></>;
}

export function LessonView({unit,lesson,onBack}:{unit:Unit;lesson:Lesson;onBack:()=>void}){
  const {state,layers,put,event,notify}=useApp();
  const stored=state.objects.sessions[lesson.id];
  const initial:Session=stored?.data||{index:0,phase:'intro',run:crypto.randomUUID(),answers:[]};
  const [local,setLocal]=useState(initial),[answer,setAnswer]=useState(initial.draft||''),[hint,setHint]=useState(false),[feedback,setFeedback]=useState<{ex:Exercise;correct:boolean|null;answer:string}|null>(null),[busy,setBusy]=useState(false),[aiFeedback,setAIFeedback]=useState('');
  const composing=useRef(false),started=useRef(Date.now()),pending=useRef(false);
  const activeTimer=useActiveTimer(local.phase==='exercise'&&!feedback&&!busy);
  const exercises=[...lesson.exercises,...(local.retry||[]).map(id=>lesson.exercises.find(e=>e.id===id)!).filter(Boolean)];
  const ex=exercises[local.index];
  async function persist(next:Session){await put({collection:'sessions',id:lesson.id,expected_version:state.objects.sessions[lesson.id]?.version||0,data:next});}
  async function begin(){setBusy(true);try{const next={...local,phase:'exercise' as const};await persist(next);setLocal(next);started.current=Date.now();}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
  async function submit(skip=false){if(!ex||pending.current||composing.current||(!answer.trim()&&!skip&&ex.kind!=='speaking'))return;pending.current=true;setBusy(true);
    const correct=skip?null:grade(ex,answer),result={id:ex.id,answer,correct,assisted:hint,skipped:skip};
    const retry=[...(local.retry||[])];if(correct===false&&local.index<lesson.exercises.length&&!retry.includes(ex.id))retry.push(ex.id);
    const next:Session={...local,index:local.index+1,answers:[...local.answers,result],retry,draft:'',phase:local.index+1>=lesson.exercises.length+retry.length?'summary':'exercise'};
    try{await event(eventFor(ex.id,ex.skill,{action_key:`lesson:${lesson.id}:${local.run}:${local.index}`,correct,answer:skip?'[bỏ qua]':answer,assisted:hint,kind:ex.kind==='speaking'?'speaking':ex.kind==='writing'?'writing':'answer',duration_ms:activeTimer.consume(),category:correct===false?errorCategory(ex):''}),{collection:'sessions',id:lesson.id,expected_version:stored?.version||0,data:next});
      setFeedback({ex,correct,answer:skip?'Đã bỏ qua; chưa tính là thành thạo.':answer});
    }catch(e){notify((e as Error).message);}finally{pending.current=false;setBusy(false);}}
  function next(){const saved=state.objects.sessions[lesson.id]?.data as Session;setLocal(saved);setFeedback(null);setAnswer('');setHint(false);setAIFeedback('');started.current=Date.now();}
  async function pause(){if(busy)return;setBusy(true);try{await persist({...local,draft:answer});notify('Đã lưu bài đang học.');onBack();}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
  async function addCards(words:Word[]){setBusy(true);try{for(const w of words){const id=w.id+':recognize';if(state.objects.cards[id])continue;await put({collection:'cards',id,expected_version:0,data:{word:{hanzi:w.hanzi,pinyin:w.pinyin,vi:w.vi},word_id:w.id,direction:'recognize',schedule:newSchedule(),deck:unit.title,tags:[],suspended:false,source:w.verification}});}notify('Đã thêm thẻ nhận diện. Các hướng khác có thể tạo trong Sổ tay.');}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
  async function feedbackAI(){if(!answer.trim())return;setBusy(true);try{const reply=await chatModel.reply([{role:'user',content:answer}],crypto.randomUUID(),'feedback');setAIFeedback(reply.hanzi+'\n'+reply.vi+'\n'+reply.feedback);}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
  return <><div className="breadcrumbs"><button onClick={onBack}>← Lộ trình</button><span>{unit.title}</span></div><h1>{lesson.title}</h1><p>{lesson.objective}</p>
    {local.phase==='intro'?<><section className="panel"><span className="eyebrow">LÀM QUEN VỚI TỪ</span><div className="word-grid">{unit.words.filter(w=>lesson.word_ids.includes(w.id)).map(w=><div className="word" key={w.id}><LayerText item={w} layers={layers}/><Speak text={w.hanzi} onError={notify}/></div>)}</div></section>{unit.grammar.filter(g=>lesson.grammar_ids.includes(g.id)).map(g=><section className="panel" key={g.id}><LayerText item={g} layers={layers}/><p>{g.explanation}</p></section>)}<section className="panel"><h3>Một cuộc trò chuyện ngắn</h3>{unit.dialogue.map((d,i)=><div className="dialogue-line" key={i}><span>{i%2===0?'A':'B'}</span><LayerText item={d} layers={layers}/><Speak text={d.hanzi} onError={notify}/></div>)}</section><button className="primary" disabled={busy} onClick={begin}>Bắt đầu luyện tập →</button></>:
    local.phase==='summary'?<><section className="panel summary"><span className="big-check">✓</span><h2>Bạn đã đi hết bài học</h2><p>{local.answers.filter(a=>a.correct===true&&!a.assisted).length} câu đúng độc lập · {local.answers.filter(a=>a.assisted).length} có gợi ý · {local.answers.filter(a=>a.skipped).length} bỏ qua</p><p>Bài nói/viết mở và câu bỏ qua không được tính thành điểm thành thạo.</p><div className="actions"><button className="primary" onClick={()=>addCards(unit.words.filter(w=>lesson.word_ids.includes(w.id)))} disabled={busy}>Thêm từ vào ôn tập</button><button onClick={async()=>{const s:Session={index:0,phase:'intro',answers:[],run:crypto.randomUUID()};try{await persist(s);setLocal(s);}catch(e){notify((e as Error).message);}}}>Học lại</button></div></section><Handwriting initial={unit.character} onComplete={character=>event(eventFor(character,'writing',{kind:'stroke'})).catch(e=>notify(e.message))}/></>:
    <section className="panel exercise"><div className="section-title"><span className="eyebrow">{feedback?'ĐỐI CHIẾU':'ĐẾN LƯỢT BẠN'}</span><span>{Math.min(local.index+1,exercises.length)}/{exercises.length}</span></div><progress value={local.index} max={exercises.length}/><h2>{ex?.prompt}</h2>
      {ex?.stimulus&&['meaning','reading','speaking'].includes(ex.kind)&&<p className="question-hanzi" lang="zh-TW">{ex.stimulus.hanzi}</p>}
      {ex?.stimulus&&['listening','dictation'].includes(ex.kind)&&<><Speak text={ex.stimulus.hanzi} onError={notify}/><small>Nếu thiếu giọng zh-TW, có thể bỏ qua câu nghe; không tính điểm nghe.</small></>}
      {feedback?<div className={'feedback '+(feedback.correct===false?'incorrect':'')}><h3>{feedback.correct===null?'Đã ghi nhận':feedback.correct?'Đúng rồi!':'Cùng xem lại nhé'}</h3><p>{feedback.answer}</p><p><strong>{feedback.ex.kind==='writing'?'Một câu tham khảo: ':'Đáp án: '}</strong>{feedback.ex.answers.join(' / ')}</p>{feedback.ex.stimulus&&<LayerText item={feedback.ex.stimulus} layers={layers} force/>}<p>{feedback.ex.explanation}</p>{feedback.correct===false&&<small>Câu này được đưa vào sổ lỗi; lần sai đầu sẽ được ôn lại sau các câu khác.</small>}<button className="primary" onClick={next}>Tiếp tục →</button></div>:<>
        {ex?.choices.length?<div className="choices">{ex.choices.map(c=><button key={c} className={answer===c?'selected':''} onClick={()=>setAnswer(c)}>{c}</button>)}</div>:<label className="answer-label">{ex?.kind==='speaking'?'Transcript (có thể sửa)':'Câu trả lời'}<textarea autoComplete="off" value={answer} onChange={e=>setAnswer(e.target.value)} onCompositionStart={()=>composing.current=true} onCompositionEnd={()=>composing.current=false} onKeyDown={e=>{if(canSubmitKey(e.nativeEvent,composing.current)&&!e.shiftKey&&ex?.kind!=='writing'){e.preventDefault();void submit();}}} placeholder={ex?.kind==='pinyin'?'Ví dụ: nǐ hǎo hoặc ni3 hao3':'Gõ Hán tự Phồn thể bằng IME…'}/></label>}
        {ex?.kind==='speaking'&&<Recorder onTranscript={setAnswer} onError={notify}/>}
        {ex?.kind==='order'&&ex.tokens?.length>0&&<div className="actions">{ex.tokens.map((token,i)=><button key={i} onClick={()=>setAnswer(answer+token)} lang="zh-TW">{token}</button>)}<button onClick={()=>setAnswer('')}>Xếp lại</button></div>}
        {ex?.kind==='writing'&&<><button disabled={busy||!answer.trim()} onClick={feedbackAI}>Góp ý bằng AI local</button>{aiFeedback&&<p className="notice pre-wrap">AI tạo, chưa đối chiếu: {aiFeedback}</p>}</>}
        {hint&&<div className="hint">Gợi ý đã được ghi nhận: {ex?.answers.join(' / ')}{ex?.stimulus&&<LayerText item={ex.stimulus} layers={layers} force/>}</div>}
        <div className="actions"><button className="primary" disabled={busy||(!answer.trim()&&ex?.kind!=='speaking')} onClick={()=>submit()}>{busy?'Đang lưu…':ex?.kind==='writing'||ex?.kind==='speaking'?'Lưu bài luyện':'Kiểm tra'}</button><button onClick={()=>setHint(true)}>Xem gợi ý</button><button disabled={busy} onClick={()=>submit(true)}>Bỏ qua câu này</button><button disabled={busy} onClick={pause}>Lưu & tạm dừng</button></div>
      </>}
    </section>}
  </>;
}
