import {useEffect,useState} from 'react';
import {useApp} from '../context';
import {initials,spellingSteps,toneMark,type Syllable} from '../core/pinyin';
import {playSamples,speech} from '../adapters/local';
import {LayerText} from './common';

export function PinyinLab(){
 const {content,notify}=useApp();const [catalog,setCatalog]=useState<Syllable[]>([]),[chosen,setChosen]=useState('ba'),[tone,setTone]=useState(1),[step,setStep]=useState(-1),[query,setQuery]=useState(''),[autoListen,setAutoListen]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch('/learning/pinyin/catalog.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error('Chưa cài gói âm mẫu Pinyin.');return r.json();}).then(setCatalog).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>{controller.abort();speech.stop();};},[]);
 const selected=catalog.find(x=>x.base===chosen)||catalog[0],sample=selected?.tones[String(tone)],steps=selected?spellingSteps(selected,tone):[];
 const spelling=selected?toneMark(selected.base,tone):'';
 const example=content.units.flatMap(u=>u.words).find(w=>w.pinyin.toLowerCase()===spelling&&Array.from(w.hanzi).length===1);
 function stop(){speech.stop();setStep(-1);}
 function choose(s:Syllable){stop();setChosen(s.base);if(autoListen)void hear(s,tone);}
 async function hear(s:Syllable,t:number){const recording=s.tones[String(t)];if(!recording)return;try{const count=spellingSteps(s,t).length;await playSamples([{label:toneMark(s.base,t),path:recording.path}],i=>setStep(i<0?-1:count-1));}catch(e){notify((e as Error).message);}}
 async function play(parts:boolean){if(!sample)return;stop();try{await playSamples(parts?steps:[{label:spelling,path:sample.path}],i=>setStep(i<0?-1:parts?i:steps.length-1));}catch(e){notify((e as Error).message);}}
 if(error)return <p className="notice">{error}</p>;
 if(!selected)return <p>Đang mở bảng ghép âm…</p>;
 return <section className="panel pinyin-lab"><span className="eyebrow">THANH MẪU · VẬN MẪU · THANH ĐIỆU</span><h2>Ghép âm Pinyin</h2><p>Bấm trực tiếp một ô âm tiết, rồi chọn thanh để nghe. Bảng xếp theo âm đầu; ∅ là âm đầu rỗng.</p>
  <div className="pinyin-quick-controls"><label>Tìm âm Pinyin<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ví dụ: ba, nü, ju…"/></label><label className="inline-check"><input type="checkbox" checked={autoListen} onChange={e=>setAutoListen(e.target.checked)}/> Nghe khi chọn âm</label></div>
  <div className="pinyin-workbench"><div className="pinyin-grid-scroll" role="region" aria-label="Bảng chọn âm Pinyin" tabIndex={0}>{initials.map(i=>{const rows=catalog.filter(s=>s.initial===i&&s.base.includes(query.trim().toLowerCase().replaceAll('v','ü').replaceAll('u:','ü')));return rows.length>0&&<div className="pinyin-grid-row" key={i}><strong className="pinyin-initial">{i||'∅'}</strong><div className="pinyin-syllables">{rows.map(s=><button key={s.base} aria-label={'Chọn âm '+s.base} aria-pressed={chosen===s.base} onClick={()=>choose(s)}>{s.base}</button>)}</div></div>;})}{!catalog.some(s=>s.base.includes(query.trim().toLowerCase().replaceAll('v','ü').replaceAll('u:','ü')))&&<p>Không có âm phù hợp. Thử bỏ dấu thanh; dùng v hoặc ü để tìm ü.</p>}</div>
  <div className="pinyin-result"><div className="tabs" aria-label="Chọn thanh điệu">{[1,2,3,4,0].map(t=><button key={t} aria-pressed={tone===t} onClick={()=>{stop();setTone(t);if(autoListen)void hear(selected,t);}}>{t?`Thanh ${t} · ${toneMark(selected.base,t)}`:'Thanh nhẹ'}</button>)}</div>
  {tone===0?<><p>Thanh nhẹ phụ thuộc âm trước và ngữ cảnh, không phải một đường cao độ cố định cho mọi âm tiết.</p><p>Ví dụ: 名字 · míngzi; 桌子 · zhuōzi. Bộ âm mẫu này chưa có bản ghi thanh nhẹ trong cụm; xem các ca nghe bên dưới.</p></>:<><strong className="syllable-result">{spelling}</strong><p>{selected.initial||'∅'} + {selected.final} + thanh {tone} → {spelling}</p><div className="spelling-steps">{steps.map((s,i)=><span key={i} className={i===step?'speaking':''}>{s.label}{i<steps.length-1?' → ':''}</span>)}</div><div className="actions"><button disabled={!sample} onClick={()=>void play(false)}>◖)) Nghe âm tiết</button><button disabled={!steps.length} onClick={()=>void play(true)}>Nghe đánh vần</button><button onClick={stop}>Dừng âm mẫu</button></div>{!sample&&<p className="notice">Chưa có âm mẫu cho âm tiết/thanh này; không thay bằng TTS.</p>}{example?<div className="pinyin-example"><small>Ví dụ từ trong gói ({example.verification==='draft'?'chưa đối chiếu':'đã đối chiếu nguồn'}):</small><LayerText item={example} layers={{hanzi:'show',pinyin:'show',vi:'show'}}/></div>:<small>Âm tiết để luyện thanh; chưa gắn từ ví dụ cho cách đọc này.</small>}</>}
  </div></div><details><summary>Cách ghép và nguồn âm mẫu</summary><p>Vận mẫu ghép được tách thành các phần để nghe chậm, rồi phát bản ghi âm tiết nguyên vẹn. Âm thành phần dùng cách đọc dạy học của MOE, có thể kèm âm đệm; không phải phụ âm thuần để nối cơ học. ian/in/ing/ong có thay đổi âm khi đọc liền. -i trong zhi/chi/shi/ri/zi/ci/si khác i trong yi; không thêm bản ghi i vào các âm này.</p><p>y/w là cách viết âm đầu rỗng; ü bỏ hai chấm sau j/q/x và trong yu. iou/uei/uen rút gọn thành iu/ui/un sau thanh mẫu.</p><p>Thành phần: 2017 © 教育部，國語注音符號手冊-開放部件 · CC BY 4.0. Âm tiết: davinfifield/mp3-chinese-pinyin-sound · Unlicense · Quan thoại phổ thông, chưa xác minh vùng giọng và chưa nghe duyệt toàn bộ. Âm lượng/giọng có thể khác giữa hai nguồn.</p><a href="/learning/licenses/moe-bopomofo.txt" target="_blank" rel="noreferrer">Giấy phép MOE</a> · <a href="/learning/licenses/pinyin-unlicense.txt" target="_blank" rel="noreferrer">Giấy phép âm tiết</a></details>
 </section>;
}
