import {useState} from 'react';
import {useApp} from '../context';
import {api} from '../adapters/local';
import {grade} from '../core/learning';
import {Speak} from './common';

export function Placement(){
 const {content,state,put,notify}=useApp();
 const questions=content.units.flatMap(u=>{
   const all=u.lessons.flatMap(l=>l.exercises);return ['meaning','order',content.units.indexOf(u)%2===0?'reading':'listening'].map(kind=>({unit:u.id,ex:all.find(e=>e.kind===kind)!}));
 });
 const saved=state.objects.placement.draft?.deleted?undefined:state.objects.placement.draft?.data;
 const [started,setStarted]=useState(Boolean(saved)),[index,setIndex]=useState(saved?.index||0),[answers,setAnswers]=useState<{unit:string;correct:boolean|null;skill:string}[]>(saved?.answers||[]),[answer,setAnswer]=useState(''),[result,setResult]=useState<string[]|null>(null),[busy,setBusy]=useState(false),[composition,setComposition]=useState(false);
 const q=questions[index];
 async function finish(list=answers){const skipped=content.units.filter(u=>{const group=list.filter(a=>a.unit===u.id);return group.length===3&&group.every(a=>a.correct===true);}).map(u=>u.id);await put({collection:'placement',id:'latest',expected_version:state.objects.placement.latest?.version||0,data:{skipped,answers:list,timestamp:new Date().toISOString()}});const fresh=await api('/state');if(fresh.objects.placement.draft)await put({collection:'placement',id:'draft',expected_version:fresh.objects.placement.draft.version,data:{index:0,answers:[]},deleted:true});setResult(skipped);}
 async function submit(skip=false){if(busy||composition)return;setBusy(true);try{const list=[...answers,{unit:q.unit,correct:skip?null:grade(q.ex,answer),skill:q.ex.skill}];await put({collection:'placement',id:'draft',expected_version:state.objects.placement.draft?.version||0,data:{index:index+1,answers:list}});setAnswers(list);if(index+1===questions.length)await finish(list);else{setIndex(index+1);setAnswer('');}}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
 return <><span className="eyebrow">BẮT ĐẦU TỪ ĐIỀU BẠN CẦN</span><h1>Kiểm tra đầu vào</h1><p>Kiểm tra trong gói nền tảng: {questions.length} câu về từ vựng, ngữ pháp, nghe và đọc. Đây là khuyến nghị lộ trình, không phải điểm TOCFL hoặc đánh giá trình độ B2.</p>{result?<section className="panel"><h2>Gợi ý vị trí bắt đầu</h2><p>Bạn có thể bỏ qua các đơn vị dưới đây hoặc mở lại bất cứ lúc nào. Không tự tạo trạng thái nhớ lâu cho flashcard, không suy ra năng lực nói/viết.</p>{content.units.map(u=><label className="check-row" key={u.id}><input type="checkbox" checked={result.includes(u.id)} onChange={e=>setResult(e.target.checked?[...result,u.id]:result.filter(id=>id!==u.id))}/>{u.title}</label>)}<button className="primary" onClick={()=>put({collection:'placement',id:'latest',expected_version:state.objects.placement.latest?.version||0,data:{...state.objects.placement.latest?.data,skipped:result}}).then(()=>notify('Đã lưu lựa chọn; mọi bài vẫn mở.')).catch(e=>notify(e.message))}>Lưu điều chỉnh</button><button onClick={()=>{setStarted(false);setResult(null);setIndex(0);setAnswers([]);}}>Làm lại kiểm tra</button></section>:!started?<section className="panel"><h2>Bạn đã biết một chút Hoa ngữ?</h2><p>Làm thử để tìm bài phù hợp. Có thể dừng sớm, bỏ câu nghe nếu chưa có giọng đọc hoặc chuyển thẳng vào học.</p><button className="primary" onClick={()=>setStarted(true)}>Bắt đầu kiểm tra</button></section>:q?<section className="panel exercise"><div className="section-title"><span>Câu {index+1}/{questions.length}</span><button disabled={busy} onClick={()=>finish().catch(e=>notify(e.message))}>Kết thúc sớm</button></div><progress value={index} max={questions.length}/><h2>{q.ex.prompt}</h2>{q.ex.stimulus&&['meaning','reading'].includes(q.ex.kind)&&<p className="question-hanzi" lang="zh-TW">{q.ex.stimulus.hanzi}</p>}{q.ex.kind==='listening'&&q.ex.stimulus&&<Speak text={q.ex.stimulus.hanzi} onError={notify}/>} {q.ex.choices.length?<div className="choices">{q.ex.choices.map(c=><button key={c} className={answer===c?'selected':''} onClick={()=>setAnswer(c)}>{c}</button>)}</div>:<textarea aria-label="Đáp án đầu vào" value={answer} onChange={e=>setAnswer(e.target.value)} onCompositionStart={()=>setComposition(true)} onCompositionEnd={()=>setComposition(false)}/>}<div className="actions"><button className="primary" disabled={busy||!answer.trim()||composition} onClick={()=>submit()}>Nộp & tiếp tục</button><button disabled={busy} onClick={()=>submit(true)}>Chưa biết / bỏ qua</button></div><small>Không hiện đáp án khi đang kiểm tra. Tiến độ kiểm tra được lưu sau mỗi câu.</small></section>:<button onClick={()=>finish().catch(e=>notify(e.message))}>Xem kết quả</button>}</>;
}
