import {useState} from 'react';
import {useApp} from '../context';
import {basicVerbs,separableVerbs,verbGroups,verbSources,verbsFor,verbTopicUnit} from '../core/verbs';
import {verbLessons,verbLessonUnit} from '../core/verbLessons';
import {newSchedule} from '../core/learning';
import type {PracticeSkill} from '../core/types';
import {PracticeText} from './PracticeText';
import {SkillPractice} from './Skills';

export function Verbs({route}:{route:string}){
 const {content,state,put,notify}=useApp(),parts=route.split('/');
 const lesson=parts[2]==='lesson'?verbLessons.find(l=>l.id===parts[3]):undefined;
 const topic=parts[2]==='topic'&&content.units.some(u=>u.id===parts[3])?parts[3]:'all';
 const skill=['listening','speaking','reading','writing'].includes(parts[4])?parts[4] as PracticeSkill:null;
 const [search,setSearch]=useState(''),[group,setGroup]=useState('all'),[stage,setStage]=useState('all'),[busy,setBusy]=useState(false);
 const title=content.units.find(u=>u.id===topic)?.title||'Tổng hợp';
 function done(id:string){return Object.values(state.objects.sessions).some(s=>!s.deleted&&s.data.unit_id==='verbs:lesson:'+id&&s.data.phase==='summary');}
 async function addCard(id:string){const v=separableVerbs.find(v=>v.id===id)!,key='verbs:card:'+id,old=state.objects.cards[key];setBusy(true);try{await put({collection:'cards',id:key,expected_version:old?.version||0,data:{word:v.split,word_id:'verbs:'+id,direction:'recognize',schedule:newSchedule(),deck:'Động từ trong câu',tags:['Động từ li hợp'],suspended:false,source:'draft'}});notify('Đã thêm cả câu tách vào thẻ ôn.');}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
 if(lesson)return <><a href="#grammar/verbs">← Chuyên đề động từ</a><h1>{lesson.title}</h1>{parts[4]==='practice'?<SkillPractice key={lesson.id} unit={verbLessonUnit(lesson.id)} skill="reading" allowAI={false}/>:<><section className="panel">{lesson.notes.map(n=><p key={n}>{n}</p>)}<p>Giải thích và bài tập do dự án biên soạn; chưa giáo viên duyệt.</p><div className="actions">{content.units.flatMap(u=>u.grammar).filter(g=>lesson.related.some(r=>(g.title||g.hanzi).includes(r))).map(g=><a key={g.id} href={'#grammar/'+g.id}>Ôn lại: {g.title||g.hanzi}</a>)}</div></section><a className="button" href={`#grammar/verbs/lesson/${lesson.id}/practice`}>Luyện bài này · 6 câu{done(lesson.id)?' · Đã hoàn thành':''} →</a></>}</>;
 return <><a href="#grammar">← Ngữ pháp</a><h1>Động từ và cách dùng</h1><p>Phân biệt số âm tiết, khả năng nhận tân ngữ và tính li hợp. Học mẫu câu trước, mở rộng từng nhóm từ sau.</p>
 <div className="unit-grid">{verbLessons.map(l=><article className="panel" key={l.id}><h2>{l.title}</h2><p>{done(l.id)?'Đã đi hết bài luyện':'6 câu luyện · tiến độ riêng'}</p><a href={'#grammar/verbs/lesson/'+l.id}>Mở bài học →</a></article>)}</div>
 <details className="panel"><summary>20 động từ cơ bản để đối chiếu</summary><p>Đơn âm/song âm không quyết định tính li hợp. Những từ dưới đây dùng nguyên từ trong các mẫu đang học; các nhãn nhận tân ngữ chỉ áp dụng cho nghĩa/mẫu đã nêu.</p><div className="unit-grid">{basicVerbs.map(v=><article key={v.hanzi}><h3 lang="zh-TW">{v.hanzi} · {v.pinyin}</h3><p>{v.vi} · {v.syllables===1?'Đơn âm':'Song âm'}</p><p>{v.object}</p><p lang="zh-TW">{v.example}</p></article>)}</div></details>
 <h2>36 động từ li hợp theo tình huống</h2><p>24 từ học trước và 12 từ mở rộng. Mỗi mục có dạng liền và một mẫu tách; không suy ra mọi kiểu tách đều áp dụng được. Nội dung bản nháp, chưa giáo viên duyệt.</p>
 <label>Chủ đề động từ<select value={topic} onChange={e=>{setGroup('all');location.hash=`grammar/verbs/topic/${e.target.value}/${skill||'guide'}`;}}><option value="all">Tất cả chủ đề</option>{content.units.map(u=><option key={u.id} value={u.id}>{u.title}</option>)}</select></label>
 <div className="tabs"><a href={`#grammar/verbs/topic/${topic}/guide`}>Tra cứu</a>{(['listening','speaking','reading','writing'] as const).map((s,i)=><a key={s} aria-current={skill===s?'page':undefined} href={`#grammar/verbs/topic/${topic}/${s}`}>Luyện {['Nghe','Nói','Đọc','Viết'][i]}</a>)}</div>
 {skill?<><p>Mỗi bộ gồm sáu từ cùng nhóm; bấm Bộ đề mới để chuyển nhóm theo vòng ôn. Nói/viết là bài mở, câu mẫu không phải đáp án duy nhất.</p><SkillPractice key={topic+skill} unit={verbTopicUnit(topic,title)} skill={skill} allowAI={false}/></>:<><div className="form-grid"><label>Tìm từ hoặc nghĩa<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Nhóm tình huống<select value={group} onChange={e=>setGroup(e.target.value)}><option value="all">Tất cả</option>{verbGroups.map((g,i)=><option key={g} value={i}>{g}</option>)}</select></label><label>Mức học<select value={stage} onChange={e=>setStage(e.target.value)}><option value="all">Tất cả</option><option value="core">Học trước</option><option value="extension">Mở rộng</option></select></label></div>
 <div className="unit-grid">{verbsFor(topic).filter(v=>(group==='all'||v.group===Number(group))&&(stage==='all'||v.stage===stage)&&(v.hanzi+v.pinyin+v.vi).toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(v=><article className="panel" key={v.id}><h3 lang="zh-TW">{v.hanzi} · {v.pinyin}</h3><p>{v.vi} · {verbGroups[v.group]} · {v.stage==='core'?'Học trước':'Mở rộng'}</p><strong>Dạng liền</strong><PracticeText key={route+v.id+'whole'} items={[v.whole]}/><strong>Một mẫu tách</strong><PracticeText key={route+v.id+'split'} items={[v.split]}/><p>{v.note}</p><button disabled={busy||!!(state.objects.cards['verbs:card:'+v.id]&&!state.objects.cards['verbs:card:'+v.id].deleted)} onClick={()=>void addCard(v.id)}>{state.objects.cards['verbs:card:'+v.id]&&!state.objects.cards['verbs:card:'+v.id].deleted?'Đã có thẻ câu này':'Thêm câu vào thẻ ôn'}</button></article>)}</div></>}
 <details><summary>Nguồn và giới hạn</summary><p>Tham khảo phân loại và giảng dạy của NTNU; câu ví dụ do dự án soạn, không phải trích nguyên giáo trình. Ranh giới giữa từ li hợp và cụm động–tân có thể khác giữa các tài liệu. Không chứng nhận audio TTS hoặc dùng ASR để chấm phát âm.</p>{verbSources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a></p>)}</details></>;
}
