import type { CardInput } from 'ts-fsrs';
export type Layers = {hanzi: 'show'|'tap'|'hide'; pinyin:'show'|'tap'|'hide'|'new'; vi:'show'|'tap'|'hide'};
export type TextItem = {hanzi:string;pinyin:string;vi:string};
export type Word = TextItem & {id:string;note:string;source:string;verification:string};
export type Grammar = TextItem & {id:string;explanation:string;title?:string;pattern?:string;restrictions?:string;common_mistake?:string;examples?:TextItem[];exercises?:Exercise[];status?:'planned'|'ready';group?:string;level?:string;prerequisites?:string[];references?:{title:string;tbcl_level:string;url:string;id:string}[]};
export type Exercise = {id:string;kind:string;prompt:string;stimulus:TextItem|null;answers:string[];choices:string[];tokens:string[];explanation:string;word_id:string|null;grammar_id?:string|null;skill:string};
export type Lesson = {id:string;title:string;objective:string;word_ids:string[];grammar_ids:string[];exercises:Exercise[]};
export type Unit = {id:string;title:string;description:string;words:Word[];grammar:Grammar[];dialogue:TextItem[];writing_prompt:string;character:string;lessons:Lesson[]};
export type GrammarRoadmap={id:string;title:string;tbcl_level:string;source:string;status:'planned';batch:number;group?:string;batch_id?:string};
export type GrammarBatch={id:string;title:string;group:string;objective:string;prerequisites:string[];source_levels:string[];status:'planned'};
export type Content = {id:string;version:number;title:string;source_note:string;units:Unit[];grammar_roadmap?:GrammarRoadmap[];grammar_batches?:GrammarBatch[]};
export type Stored<T=Record<string,unknown>> = {version:number;deleted:boolean;data:T};
export type Collection = 'sessions'|'cards'|'notes'|'settings'|'placement'|'chats'|'reports';
export type LearningEvent = {id:string;action_key:string;kind:string;skill:string;item_id:string;correct:boolean|null;assisted:boolean;answer:string;duration_ms:number;algorithm:string;timestamp:string;category:string;rating?:number};
export type AppState = {device_id:string;objects:Record<Collection,Record<string,Stored<any>>>;events:LearningEvent[]};
export type Mutation = {collection:Collection;id:string;expected_version:number;data:object;deleted?:boolean};
export type Session = {index:number;phase:'intro'|'exercise'|'summary';run:string;answers:{id:string;answer:string;correct:boolean|null;assisted:boolean;skipped?:boolean}[];draft?:string;retry?:string[];assisted?:boolean};
export type Flashcard = {word:TextItem;word_id:string;direction:'recognize'|'produce'|'audio'|'write'|'cloze'|'situation';schedule:CardInput;deck:string;tags:string[];suspended:boolean;source:string;cue?:string};
export type AIReply = TextItem & {feedback:string;elapsed_ms:number;generated:boolean;quality_warnings?:string[];annotation_source?:string};
export type Status = {llm_installed:boolean;llm_running:boolean;asr_installed:boolean;tts_voices:string[];error:string;model:string;asr:string;quality:string;sizes:Record<string,number>;budget_bytes:number;config:{model:string;runtime:string;asr_model:string};available_models:string[];available_asr_models:string[];cuda_installed:boolean};
export type ChatTurn = {role:'user'|'assistant';content:string;reply?:AIReply};
